# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1706211769c070788541b7f593b431f"
name = "AI poster generation"
handle = "ai-poster-generation"
application_url = "https://entrepreneurs-derek-upcoming-mood.trycloudflare.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-567e25b4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://entrepreneurs-derek-upcoming-mood.trycloudflare.com/auth/callback",
  "https://entrepreneurs-derek-upcoming-mood.trycloudflare.com/auth/shopify/callback",
  "https://entrepreneurs-derek-upcoming-mood.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false

